### ISSUE TITLE
Add alternative browser chooser to this site

### ISSUE THREAD

**Issue by MaxValue** [MicrosoftEdge/microsoftedge.github.io#1]
Even if I can't see this repo; Windows 10 still opens this site on the first start of Edge.

Problem here: This browser does not ask the user if he/she wants to actually use a different browser upon first start.

Microsoft Internet Explorer had this feature, since the European Union forced Microsoft to implement it.

Now we have the same problem again. Microsoft could avoid financial losses and unnecessary legal disputes with the European Union by simply providing links to other major browsers, like Microsoft Internet Explorer did.

**Comment by molant** [comment]
If I understood you correctly, what you are requesting is a windows feature and not an edge one.
You should use the feedback application in Windows 10 for this.

**Comment by MaxValue** [comment]
Nobody reads the feedback on the Windows 10 "Feedback Application". It's dead, Jim.

Since Edge is an essential part of Windows 10 (it cannot be uninstalled), it should be treated as one. Therefore it should provide the option to choose another browser upon first start. 

(Don't tell me you maintain a "Windows" Edge version _and_ a "General" Edge version which behave differently upon start?)

**Comment by molant** [comment]
We do read the feedback application. It's how we get reports for bugs, new features, etc. for windows and windows applications. If you don't want to use the proper channel to communicate with the team that's up to you, but this is not the place.
